# Generated by Django 3.1.3 on 2020-12-01 18:18


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = ('MyAIApp', '0001_initial'),

    operations = \
        migrations.RenameModel(
            old_name='MyPlus1RuleModel',
            new_name='MyPlusNRuleModel'
        ),
